import { ArrowRight, BriefcaseBusiness, Building2, Mail, ShieldCheck } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link } from 'wouter';
import { openConsentPreferences } from '@/lib/consent';

export type TrustPageKind = 'about' | 'contact' | 'privacy' | 'terms' | 'cookies' | 'data' | 'support' | 'advertise';

const SUPPORT_EMAIL = 'nsukumasaka@gmail.com';

const PAGE_INTROS: Record<TrustPageKind, { title: string; description: string }> = {
  about: { title: 'About BonList', description: 'BonList is a South African career platform built to help job seekers prepare clearer applications and make more informed career decisions.' },
  contact: { title: 'Contact BonList', description: 'Contact us about product support, privacy, recruiter collaboration or responsible commercial opportunities.' },
  privacy: { title: 'Privacy Policy', description: 'This page explains how BonList handles account information, uploaded CVs and optional browser technologies.' },
  terms: { title: 'Terms of Use', description: 'These terms describe the responsible use of BonList career tools and services.' },
  cookies: { title: 'Cookie Policy and Preferences', description: 'Understand the essential and optional browser storage used by BonList.' },
  data: { title: 'Data Handling and Deletion', description: 'Learn how BonList handles stored CV information and how to request access or deletion.' },
  support: { title: 'Contact and Support', description: 'Get help with your account, CV workspace, uploads, downloads or privacy requests.' },
  advertise: { title: 'Work with BonList', description: 'Enquire about future employer, recruiter and responsible advertising opportunities.' },
};

function PageShell({ kind, children }: { kind: TrustPageKind; children: ReactNode }) {
  const page = PAGE_INTROS[kind];
  return <main className="mx-auto min-h-[60vh] w-full max-w-4xl min-w-0 overflow-x-hidden px-4 py-10 sm:px-5 md:px-8 md:py-16"><nav aria-label="Breadcrumb" className="text-xs text-muted-foreground"><Link href="/" className="hover:text-primary">Home</Link><span className="mx-2" aria-hidden>/</span><span aria-current="page">{page.title}</span></nav><header className="mt-8 border-b border-border pb-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">BonList</p><h1 className="display mt-3 break-words text-3xl font-semibold text-foreground sm:text-4xl md:text-5xl">{page.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground">{page.description}</p></header><div className="mt-9 space-y-9 text-sm leading-7 text-muted-foreground">{children}</div></main>;
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section><h2 className="text-xl font-semibold text-foreground">{title}</h2><div className="mt-3 space-y-3">{children}</div></section>;
}

export function TrustPage({ kind }: { kind: TrustPageKind }) {
  if (kind === 'about') return <PageShell kind={kind}><Section title="What BonList does"><p>BonList combines CV creation, CV review, job matching, interview preparation and career support in one workspace. The platform is designed around truthful candidate information: users should verify every generated suggestion before using it.</p></Section><Section title="Who it is for"><p>BonList serves job seekers preparing for opportunities in South Africa, including people entering the workforce, changing careers or improving an established professional profile.</p></Section><Section title="Our approach"><p>Career tools should clarify a person’s real experience rather than invent achievements. Match scores and guidance are decision-support tools; they do not guarantee interviews, offers or recruitment-system outcomes.</p></Section><div className="flex flex-wrap gap-2"><Link href="/career-advice" className="btn-primary">Read career advice <ArrowRight size={14} /></Link><Link href="/contact" className="btn-secondary">Contact BonList</Link></div></PageShell>;

  if (kind === 'contact' || kind === 'support') return <PageShell kind={kind}><div className="grid gap-4 sm:grid-cols-2"><section className="border border-border bg-card p-5"><Mail size={20} className="text-primary" /><h2 className="mt-4 text-lg font-semibold text-foreground">User and privacy support</h2><p className="mt-2 text-sm leading-6">For account, CV, upload, download, access or deletion questions, email <a href={`mailto:${SUPPORT_EMAIL}?subject=BonList support request`} className="font-semibold text-primary hover:underline">{SUPPORT_EMAIL}</a>.</p></section><section className="border border-border bg-card p-5"><Building2 size={20} className="text-primary" /><h2 className="mt-4 text-lg font-semibold text-foreground">Business enquiries</h2><p className="mt-2 text-sm leading-6">Employers, recruiters and potential partners can email <a href={`mailto:${SUPPORT_EMAIL}?subject=BonList business enquiry`} className="font-semibold text-primary hover:underline">{SUPPORT_EMAIL}</a> with a clear organisation name and proposal.</p></section></div><Section title="Please protect your information"><p>Do not send passwords, one-time PINs, full identity numbers, banking credentials or payment-card details. For account-specific requests, contact us from the email address associated with your BonList account.</p></Section><Section title="Helpful details to include"><ul className="list-disc space-y-1 pl-5"><li>The page or feature involved.</li><li>A short description of what happened.</li><li>Your browser or phone type when relevant.</li><li>A screenshot with sensitive information removed.</li></ul></Section></PageShell>;

  if (kind === 'privacy') return <PageShell kind={kind}><p className="border-l-4 border-amber-400 bg-amber-50 px-4 py-3 text-amber-950">This operational policy describes the current product architecture and should be reviewed by a qualified South African privacy professional before being treated as legal advice.</p><Section title="Information used to provide BonList"><p>BonList may process account details, profile preferences, uploaded CV documents, extracted CV information, saved CV versions, CV reviews, job-match inputs and support messages when you ask the platform to provide those features.</p></Section><Section title="Uploaded CVs"><p>CVs contain personal information. BonList uses uploaded content to perform the requested extraction, editing, review, storage and matching functions. CV contents must not be placed in public metadata, public structured data, advertising requests or analytics events.</p></Section><Section title="Service providers and processing"><p>BonList may rely on hosting, database, email, document-processing, authentication, payment or AI service providers where required to deliver a requested feature. Access should be limited to the purpose of providing and securing the service.</p></Section><Section title="Optional analytics and advertising"><p>Optional analytics and advertising technologies must respect the consent choice stored in your browser. Advertising is currently disabled. If it is enabled later, this policy and the consent interface must be updated with accurate provider information before activation.</p></Section><Section title="Retention, access and deletion"><p>Retention depends on the type of record and operational or legal needs. You can manage saved CVs in the product and request account or data assistance through the contact page. BonList may need to verify a request before acting on it.</p></Section><Section title="Security and your choices"><p>No online system can promise absolute security. Use a strong password, protect your device and avoid uploading unnecessary sensitive information. You may reject optional browser technologies without losing essential account functions.</p></Section><p className="text-xs">Last updated: 2 October 2026.</p></PageShell>;

  if (kind === 'terms') return <PageShell kind={kind}><p className="border-l-4 border-amber-400 bg-amber-50 px-4 py-3 text-amber-950">These terms require professional legal review before commercial reliance.</p><Section title="Responsible use"><p>Use BonList for lawful career preparation and provide truthful information. Do not upload content you do not have permission to use, attempt to access another person’s account, interfere with the service or use the platform to mislead employers.</p></Section><Section title="Career guidance"><p>CV suggestions, scores, job matches and interview guidance are advisory. BonList does not guarantee an interview, employment offer, salary, recruitment-system result or employer response.</p></Section><Section title="Your documents"><p>You remain responsible for reviewing the accuracy and suitability of every CV, application and message before submitting it. Automated suggestions can be incomplete or incorrect.</p></Section><Section title="External vacancies and links"><p>Job information may originate from external sources. Verify the employer, vacancy, closing date and application method on the source site. BonList is not the employer unless a page clearly states otherwise.</p></Section><Section title="Changes and availability"><p>Features may change as the product develops. Material commercial or privacy changes should be communicated appropriately. Contact BonList if you need help understanding a current feature.</p></Section><p className="text-xs">Last updated: 2 October 2026.</p></PageShell>;

  if (kind === 'cookies') return <PageShell kind={kind}><Section title="Essential storage"><p>Essential storage supports sign-in security, saved preferences, session continuity and other core functions. These functions cannot always be disabled through the consent panel because the requested service may not work without them.</p></Section><Section title="Optional analytics"><p>Optional analytics may be used to understand page and feature usage. Analytics events must not include CV text, identity numbers, passwords, payment data or unnecessary personal information.</p></Section><Section title="Optional advertising"><p>No advertising provider is currently active. The architecture keeps advertising disabled unless BonList has authorised credentials and the user’s consent where required. Ads are excluded from private and productivity areas such as the CV Builder, dashboard, account and administration pages.</p></Section><button type="button" onClick={openConsentPreferences} className="btn-primary">Manage cookie preferences</button><p className="text-xs">Last updated: 2 October 2026.</p></PageShell>;

  if (kind === 'data') return <PageShell kind={kind}><Section title="Managing saved CVs"><p>Use My Resumes to review and manage saved documents available through your account. Confirm that you are working in the correct account before deleting information.</p></Section><Section title="Requesting access or deletion"><p>Email <a href={`mailto:${SUPPORT_EMAIL}?subject=BonList data request`} className="font-semibold text-primary hover:underline">{SUPPORT_EMAIL}</a> from the address linked to your account. State whether you are requesting access, correction or deletion. Do not attach identity documents unless BonList requests a suitable verification method.</p></Section><Section title="What happens next"><p>BonList may need to verify account ownership, clarify the scope and retain limited information where required for security, fraud prevention, transactions or legal obligations. This page does not promise a response period that has not been legally reviewed.</p></Section></PageShell>;

  return <PageShell kind="advertise"><div className="grid gap-4 sm:grid-cols-2"><section className="border border-border bg-card p-5"><BriefcaseBusiness size={20} className="text-primary" /><h2 className="mt-4 text-lg font-semibold text-foreground">Employer opportunities</h2><p className="mt-2 text-sm leading-6">Future options may include featured jobs, sponsored vacancies and employer profiles. These products are not currently self-service.</p></section><section className="border border-border bg-card p-5"><ShieldCheck size={20} className="text-primary" /><h2 className="mt-4 text-lg font-semibold text-foreground">Responsible advertising</h2><p className="mt-2 text-sm leading-6">BonList will prioritise clear labelling, relevant placements and an ad-free private CV workspace. Fake vacancies and misleading promotions are not acceptable.</p></section></div><Section title="Start an enquiry"><p>Email <a href={`mailto:${SUPPORT_EMAIL}?subject=BonList advertising or employer enquiry`} className="font-semibold text-primary hover:underline">{SUPPORT_EMAIL}</a> with your organisation, objective, proposed campaign and intended audience. Do not send payment information in the first message.</p></Section><p className="text-xs">Availability, pricing and acceptance criteria have not yet been published. Sending an enquiry does not guarantee placement.</p></PageShell>;
}
